version: "3.8"

services:
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:ubuntu-5.4-latest
  container_name: zabbix-server
  expose:
    - 10051
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
    - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
    - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
    - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
    - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  env_file:
    - ./env_vars/.env_db_pgsql
    - ./env_vars/.env_srv
  secrets:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
  depends_on:
    - postgres-server
  networks:
    - zbx_net_backend
    - web_proxy
  stop_grace_period: 30s
  sysctls:
    - net.ipv4.ip_local_port_range=1024 65000
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.secure_redirects=0
    - net.ipv4.conf.all.send_redirects=0
  labels:
    - com.zabbix.description="Zabbix server with PostgreSQL database support"
    - com.zabbix.company="Zabbix LLC"
    - com.zabbix.component="zabbix-server"
    - com.zabbix.dbtype="pgsql"
    - com.zabbix.os="ubuntu"
#    - traefik.docker.network=web_proxy
#    - traefik.http.routers.zabbix-server.rule=Host(`zabbix-server.example.com`)
#    - traefik.http.routers.zabbix-server.tls=true
#    - traefik.http.routers.zabbix-server.tls.certresolver=lets-encrypt
#    - traefik.port=10051
  restart: always

 zabbix-web:
  image: zabbix/zabbix-web-apache-pgsql:ubuntu-5.4-latest
  container_name: zabbix-apache
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  env_file:
   - ./env_vars/.env_db_pgsql
   - ./env_vars/.env_web
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://zabbix-web:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   - zbx_net_backend
   - web_proxy
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
    - com.zabbix.description="Zabbix frontend on Nginx web-server with PostgreSQL database support"
    - com.zabbix.company="Zabbix LLC"
    - com.zabbix.component="zabbix-frontend"
    - com.zabbix.webserver="nginx"
    - com.zabbix.dbtype="pgsql"
    - com.zabbix.os="ubuntu"
    - traefik.docker.network=web_proxy
    - traefik.http.routers.zabbix-web.rule=Host(`zabbix.example.com`)
    - traefik.http.routers.zabbix-web.tls=true
    - traefik.http.routers.zabbix-web.tls.certresolver=lets-encrypt
    - traefik.port=8080
  restart: always

 zabbix-agent:
  image: zabbix/zabbix-agent:ubuntu-5.4-latest
  container_name: zabbix-agent
  expose:
   - 10050
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  env_file:
   - ./env_vars/.env_agent
  networks:
   - zbx_net_backend
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "ubuntu"
  restart: always
 
  postgres-server:
  image: postgres:13-alpine
  container_name: zabbix-postgres
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
  env_file:
   - ./env_vars/.env_db_pgsql
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  stop_grace_period: 1m
  networks:
    - zbx_net_backend
  restart: always

networks:
  web_proxy:
    external: true
  zbx_net_backend:
    external: false

secrets:
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD
